### PR TITLE
fix(llcppsymg): clean path for presumed location

### LINKED ISSUE #479: Unexpected path comparison
I'm converting `lvgl` with `llcppg`, and found this error

```
panic: File "/Users/xxx/lvgl/src/core/../lv_conf_internal.h" not found in FileMap. Available files:
```

Actually, the real path of `lv_conf_internal.h` is `/Users/xxx/lvgl/src/lv_conf_internal.h` .

# How to reproduce

## 1. Build LVGL
```bash
mkdir build && cd build
cmake ..
cmake --build .
```

## 2. Add `pkgconfig`

```
includedir="/Users/xxx/lvgl"
libdir="${includedir}/build/lib"

Name: lvgl
Description: Light and Versatile Graphics Library
URL: https://lvgl.io/
Version: 9.3.0
Cflags: -I${includedir}
Libs: -L${libdir} -llvgl
```

And activate it, `export PKG_CONFIG_PATH=$(pwd):$PKG_CONFIG_PATH`

## 3. Generate `llcppg.cfg`
```
llcppcfg -excludes "tests demos src examples build libs env_support" lvgl
```

## 4. Generate with `llcppg`
```
llcppg
```

### PR DESCRIPTION
**Pull request by MeteorsLiu**
Fixes #479

### CODE REVIEW

File: _xtool/internal/parser/parser.go [hunk 1]
```diff
@@ -139,8 +139,7 @@ func (ct *Converter) logln(args ...interface{}) {
 
 func (ct *Converter) InFile(cursor clang.Cursor) bool {
```
Comment (luoliwoshang) [inline _xtool/internal/parser/parser.go:140]: also can update~
```go
func createLoc(cursor clang.Cursor) *ast.Location {
	var file clang.String
	loc := cursor.Location()
	loc.PresumedLocation(&file, nil, nil)
	filename := filepath.Clean(clang.GoString(file))
	return &ast.Location{
		File: filename,
	}
}
```

File: _xtool/llcppsymg/internal/symg/parse.go
[the remark this answers is not in the document]
Comment (MeteorsLiu) [reply _xtool/llcppsymg/internal/symg/parse.go:1]: Done in [test: add test for llcppsymg](https://github.com/goplus/llcppg/pull/485/commits/8f2d426a08222d75e81b6d2faabeca73b1a93141)

File: _xtool/llcppsymg/internal/symg/testdata/include/src/conf.h [hunk 2]
```diff
@@ -0,0 +1 @@
+void Foo_Conf();
```
Comment (luoliwoshang) [inline _xtool/llcppsymg/internal/symg/testdata/include/src/conf.h:1]:
```suggestion
void Foo_Conf();

```

**Review by luoliwoshang — APPROVED** [review]
